# gitlab pipeline to publish coverage reports

image: curlimages/curl:latest

variables:
  PKG_VERSION: 2021.0402.1225

stages:
  - deploy
  - release

pages:
  stage: deploy
  only:
    - dev-ops
  script:
    - mkdir coverage/
    - shell/fetch-cover-zip.sh
    - unzip coverage.zip -d coverage/
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 5 days

release_upload:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli
  needs:
    - job: pages
  rules:
    - if: $CI_COMMIT_BRANCH == 'dev-ops'
    - if: $CI_COMMIT_TAG
      when: never
  script:
    - shell/make-release.sh
