# hoot-smalltalk google cloud build
steps:
  # pull docs bundle
  - name: 'maven:3-eclipse-temurin-17'
    id: pull_bundle
    entrypoint: 'bash'
    args: [ '-c', "docs/fetch-docs-bundle.sh" ]

#options:
   # build normal with 8 cores
   #machineType: 'N1_HIGHCPU_8'
