# hoot-smalltalk google cloud build
steps:
  # confirm sources
  - name: 'gcr.io/cloud-builders/gcloud'
    id: pull_sources
    entrypoint: 'bash'
    args: [ '-c', "chmod +x docs/*.sh; chmod +x shell/*.sh" ]

  # install tools
  - name: 'gcr.io/cloud-builders/gcloud'
    id: install_tools
    entrypoint: 'bash'
    args: [ '-c', "shell/install-tools.sh" ]
    waitFor:
      - pull_sources

  # fetch account secrets
  - name: 'gcr.io/cloud-builders/gcloud'
    id: fetch_secrets
    entrypoint: 'bash'
    args: [ '-c', "shell/fetch-secrets.sh" ]
    waitFor:
    - install_tools

  # pull docs bundle
  - name: 'maven:3-eclipse-temurin-17'
    id: pull_bundle
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export MAVEN_REPO_PASS=$(echo "$(< /workspace/hoot-secret-github.txt)")
        shell/pull-lib.sh hoot-docs-bundle jar $TAG_NAME
        docs/copy-docs-bundle.sh $TAG_NAME
    env:
      - 'MAVEN_REPO_USER=nikboyd'
      - "TAG_NAME=$TAG_NAME"
    waitFor:
      - fetch_secrets

  # build container image
  - name: 'gcr.io/cloud-builders/docker'
    id: build_image
    automapSubstitutions: true
    script: |
      export DOCS_TAG=$( date +"%Y.%m%d.%H%M" )
      echo "$DOCS_TAG" > /workspace/hoot-docs-host-tag.txt
      docker build -t $DOCS_PACK/$PROJECT_ID/$DOCS_REPO/$DOCS_HOST:$DOCS_TAG -f $DOCS_FILE docs
      docker push $DOCS_PACK/$PROJECT_ID/$DOCS_REPO/$DOCS_HOST:$DOCS_TAG
    env:
      - 'DOCS_REGION=us-west1'
      - 'DOCS_PACK=us-west1-docker.pkg.dev'
      - 'DOCS_REPO=hoot-docs-images'
      - 'DOCS_HOST=hoot-docs-host'
      - 'DOCS_FILE=docs/hoot-docs-dockerfile'
    waitFor:
    - pull_bundle

  # run container
  - name: 'gcr.io/cloud-builders/gcloud'
    id: run_docs
    entrypoint: 'bash'
    args: [ '-c', "gcloud run deploy hoot-docs-host --region us-west1 --image us-west1-docker.pkg.dev/$PROJECT_ID/hoot-docs-images/hoot-docs-host:$(< /workspace/hoot-docs-host-tag.txt)" ]
    waitFor:
    - build_image
