# hoot-smalltalk google cloud build
steps:
  # build check run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: check_run
    entrypoint: 'bash'
    args: [ '-c', "echo 'cloud build'" ]

#options:
   # build normal with 8 cores
   #machineType: 'N1_HIGHCPU_8'
