# hoot smalltalk build pipeline

name: hoot-build-pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: build-main-branch
        run: |
          mvn --version
          shell/build-all-mods.sh
      - name: upload-bundles
        run: |
          mvn -U -B -pl hoot-compiler-bundle,hoot-maven-plugin,hoot-libs-bundle deploy

#      - name: stage-bundles
#        run: |
#          mkdir bundle-stage
#          cp hoot-maven-plugin/target/*.jar bundle-stage
#          cp hoot-libs-bundle/target/*.jar  bundle-stage
#          cp hoot-compiler-bundle/target/*.jar bundle-stage
#      - uses: actions/upload-artifact@v2
#        with:
#          name: Package
#          path: bundle-stage
