# hoot smalltalk build pipeline

name: hoot-build-pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: build-main-branch
        env:
          MAVEN_REPO_USER: ${{ secrets.MAVEN_REPO_USER }}
          MAVEN_REPO_PASS: ${{ secrets.MAVEN_REPO_PASS }}
          MAVEN_CLOUD_USER: ${{ secrets.MAVEN_CLOUD_USER }}
          MAVEN_CLOUD_PASS: ${{ secrets.MAVEN_CLOUD_PASS }}
        run: |
          mvn --version
          shell/build-all-mods.sh
