# hoot smalltalk build pipeline

name: hoot-build-pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: build-main-branch
        env:
          MAVEN_REPO_USER: ${{ secrets.MAVEN_REPO_USER }}
          MAVEN_REPO_PASS: ${{ secrets.MAVEN_REPO_PASS }}
        run: |
          echo "$MAVEN_REPO_USER"
          mvn --version
          shell/build-all-mods.sh
#      - name: stage-coverage
#        run: |
#          mkdir coverage-stage
#          cp coverage.zip coverge-stage
#      - uses: actions/upload-artifact@v2
#        with:
#          name: Coverage
#          path: coverge-stage
