# hoot smalltalk build pipeline

name: hoot-build-pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: build-main-branch
        run: |
          pwd
          ls -al
          mvn --version
          sysctl -n hw.physicalcpu
